[package]
name = "rust-raytracer"
version = "0.1.0"
authors = [
    "ng.guoyou@gmail.com",
    "stacey.ell@gmail.com"
]

[dependencies]
num = "*"
rand = "*"

[target.'cfg(target_os = "wasi")'.dependencies]
wasi-rng = "*"

