[package]
name = "raylib"
version = "0.1.0"
authors = [
    "ng.guoyou@gmail.com",
    "stacey.ell@gmail.com"
]

[dependencies]
num-traits = "*"
rand = "*"

[target.'cfg(target_os = "wasi")'.dependencies]
wasi-rng = "*"

