[package]
name = "raytracer"
version = "0.1.0"
edition = "2018"
authors = [
    "ng.guoyou@gmail.com",
    "stacey.ell@gmail.com"
]
metadata.wasm-opt = false

[dependencies.rand]
version="*"

[dependencies.num-traits]
version="*"

